include "#!./gradlew -q composeApp:printConveyorConfig"
include "/stdlib/jdk/21/amazon.conf"

app {
    machines = [windows.amd64, linux.aarch64, linux.arm64, mac.aarch64]

    display-name = "Chirp"
    fsname = "chirp"
    vendor = "Gaddal Dev"
    description = "Chirp Chat Application"
    rdns-name = "dev.gaddal.chirp"

    url-schemes = ["chirp"]

    inputs += "composeApp/build/libs/composeApp-desktop-*.jar"

    icons = "conveyorResources/logo.png"

    single-instance = true

    license = "MIT"
    copyright = "© 2025 Gaddal Dev"
    vcs-url = "https://github.com/IronManYG/Chirp"
    updates = none

    jvm {
        main-class = "dev.gaddal.chirp.MainKt"
        gui.main-class = "dev.gaddal.chirp.MainKt"

        version = 21

        options = [
            "-Xmx2g",
            "--add-opens=java.base/sun.misc=ALL-UNNAMED",
            "--add-opens=java.base/java.nio=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt.wl=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED",
        ]

        modules = [
            java.desktop,
            java.logging,
            java.prefs,
            java.sql,
            jdk.unsupported
        ]
    }

    mac {
        info-plist {
            "com.apple.developer.associated-domains" = [
                "applinks:chirp.pl-coding.com"
            ]
        }
    }
}

conveyor {
    compatibility-level = 19
    billing-email = "mail@gaddal.dev"
}