package dev.gaddal.chirp.convention

import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

/**
 * Configures iOS targets for Kotlin Multiplatform projects.
 *
 * This method sets up the required iOS targets (`iosX64`, `iosArm64`, `iosSimulatorArm64`)
 * in the Kotlin Multiplatform extension. For each target, it configures a static framework
 * with the base name "ComposeApp".
 *
 * The frameworks generated by this configuration can be used to integrate Kotlin code
 * with iOS applications.
 *
 * This function is intended for use within a Gradle project using the Kotlin Multiplatform plugin.
 */
internal fun Project.configureIosTargets() {
    extensions.configure<KotlinMultiplatformExtension> {
        listOf(
            iosX64(),
            iosArm64(),
            iosSimulatorArm64()
        ).forEach { iosTarget ->
            iosTarget.binaries.framework {
                baseName = "ComposeApp"
                isStatic = true
            }
        }
    }
}